### ISSUE TITLE
v2.0.1: doRemoveWhitespaceAroundTags(false) both inserts spaces and removes spaces in places where it shouldn't

### ISSUE THREAD

**Issue by Bilge** [voku/HtmlMin#13]
## Erroneous insertion case

There are no spaces between tags in this input.

```html
 <span class="foo"><span title="bar"></span><span title="baz"></span><span title="bat"></span></span>
```

HtmlMin injects spaces between all these tags, but only when `doRemoveWhitespaceAroundTags` is set to `false`.

```html
<span class=foo><span title=bar></span> <span title=baz></span> <span title=bat></span> </span>
```

HtmlMin should absolutely not be introducing whitespace where none existed, no matter what settings are used, because this affects the content.

## Erroneous removal case

Given the following input:

```html
                        <span class="title">
                1.
                <a>Foo</a>
            </span>
```

HtmlMin removes white-space after the closing `</a>` tag despite `doRemoveWhitespaceAroundTags(false)` being set. This affects how the content is displayed.

```html
<span class=title> 1. <a>Foo</a></span>
```

**Comment by voku** [comment]
First, thanks for testing :+1: 

I have changed the behavior, only if the next sibling child element is a "DOMText" we will now add the whitespace. I hope this behavior is more correct, maybe we can also disable "doRemoveWhitespaceAroundTags" by default?

PS: your examples are now implemented as unit-tests -> https://github.com/voku/HtmlMin/commit/46a8a1d91ff35587adfbda00dae72aaa99f5ef9f#diff-468b8a043eb54ed31edbee53141c1512R253

**Comment by Bilge** [comment]
To be clear, I am not just *testing*, I'm using HtmlMin in production so it's very important to me to see its working correctly. Thanks for your prompt responses 👍 

I completely agree removing whitespace around tags should be disabled by default because I do not think the default operation should apply "risky" fixes that could alter the presentation.
