### ISSUE TITLE
v2.0.2 Disappearing whitespace between </dl> and <a>

### ISSUE THREAD

**Issue by Bilge** [voku/HtmlMin#14]
Given the following input:

```html
            <dl>
                <dt>foo
                <dd><span class="bar"></span>
            </dl>
            <a class="baz"></a>
```

Becomes:

```html
<dl><dt>foo <dd><span class=bar></span> </dl><a class=baz></a>
```

This is incorrect because the space between the closing `</dl>` and opening `<a>` has completely disappeared.

**Comment by voku** [comment]
Hi, I have found the issue... :/ the problem was that "dom->loadHTML()" without "LIBXML_HTML_NODEFDTD" will not keep the white-spaces.

**Comment by Bilge** [comment]
@voku Merry Christmas and thanks for your work! 🎅 

I will of course be testing it when a tag is available and hopefully I won't need to create any more issues 😁

**Comment by voku** [comment]
@Bilge I wish you also some nice christmas days   🎅
