### ISSUE TITLE
More W3C validator errors after minify

### ISSUE THREAD

**Issue by shyim** [voku/HtmlMin#25]
#### What is this feature about (expected vs actual behaviour)?

Html minified has more errors then before in W3C Validator.

#### How can I reproduce it?
https://dpaste.de/i72Q gives in Validator 8 warnings/errors
After minify i have 11 warning/errors

Used following code
```
$html = (new \voku\helper\HtmlMin())->minify($html)
```

#### Does it take minutes, hours or days to fix?
No idea

#### Any additional information?

**Comment by PicPS98** [comment]
I habe the same issue, the DOCTYPE, end the Closing </html> tag was Removed

**Comment by voku** [comment]
The dpaste link is a 404... so can you please answer again the question: "How can I reproduce it?"
