### ISSUE TITLE
html tag for AMP is modifed incorrectly

### ISSUE THREAD

**Issue by scones** [voku/HtmlMin#36]
#### What is this feature about (expected vs actual behaviour)?
To use AMP properly, one has to use a specific html tag
`<html ⚡>`

unfortunately HtmlMin removed the important bit, leaving only
`<html>`

#### How can I reproduce it?
run the minifier over a sample document with the tag sahown above

#### Does it take minutes, hours or days to fix?
depending on the source of the problem and how much you are into your code:
hours to days

#### Any additional information?
-

**Comment by voku** [comment]
thanks for the bug report, fixed in version 4.5.4 ... but you can also use ```<html amp>``` like this https://amp.dev/documentation/guides-and-tutorials/start/create/basic_markup?format=websites

**Comment by scones** [comment]
your fix now produced `<html ____simple_html_dom__voku__google_amp____=true>` which is invalid again

**Comment by voku** [comment]
I added a test case... 🤔 but maybe you are using the lib a different way, so can you share a minimal example or even better a pull request with a failed test? Thanks.

**Comment by scones** [comment]
well, my config looks like this:

**Comment by voku** [comment]
my fault :/ ... I didn't tested it via HtmlMin (I only fixed and tested it via SimpleHtmlDom) but HtmlMin will remove the quotes from a helper string ```...="true"``` vs. ```...=true```. 

Fixed in version 3.1.8 of HtmlMin (https://github.com/voku/HtmlMin/commit/f7256e7b3fb00c1873207aa269eaa66ae8f0ba8a)
