### ISSUE TITLE
incorrect processing with Attributes html 

### ISSUE THREAD

**Issue by storm1101** [voku/HtmlMin#37]
#### Any additional information?

**Comment by storm1101** [comment]
This html code has an incorrect processing:

 <button type="button" id="rotate_crop" class="btn btn-primary" data-loading-text="<i class='fa fa-spinner fa-spin'></i> Rotando..." style="">Rotar</button>

$htmlMin = new HtmlMin();

echo $htmlMin->minify("<button type=\"button\" id=\"rotate_crop\" class=\"btn btn-primary\" data-loading-text=\"<i class='fa fa-spinner fa-spin'></i> Rotando...\" style=\"\">Rotar</button>");

Bad Output is: button type="button" id="rotate_crop" class="btn btn-primary" data-loading-text="<i class='fa fa-spinner fa-spin'></i> Rotando..." style=""</button>

When it had to be: <button type="button" id="rotate_crop" class="btn btn-primary" data-loading-text="<i class='fa fa-spinner fa-spin'></i> Rotando..."> style=""</button>

**Comment by storm1101** [comment]
button type="button" id="rotate_crop" class="btn btn-primary" data-loading-text="<i class='fa fa-spinner fa-spin'></i> Rotando..." style=""</button>

**Comment by voku** [comment]
Hi, I added a test case here "https://github.com/voku/HtmlMin/commit/1b6d9cdeb25286dfae4720f9663df7a6978e18b6" but it passed and I can't see the issue? Maybe you are not using the current version of HtmlMin? https://github.com/voku/HtmlMin/blob/master/CHANGELOG.md

**Comment by voku** [comment]
Please feel free to re-open the issue if this is still a problem for you.
