### ISSUE TITLE
Too many single white spaces are removed

### ISSUE THREAD

**Issue by Kubik-Rubik** [voku/HtmlMin#41]
Hey @voku,

thanks for the great script!

Though, I have a small issue with the latest version. Single white spaces are removed between span elements. In my case only the first white space is preserved, all other for the next span elements are removed. The problem is that buttons are loaded via CSS and with the optimization they are glued together.

Original:

```<p><span class="label-icons">XXX</span> <span class="label-icons label-free">FREE</span> <span class="label-icons label-pro">PRO</span> <span class="label-icons label-popular">POPULAR</span> <span class="label-icons label-community">COMMUNITY CHOICE</span></p>```

Minified:

```<p><span class="label-icons">XXX</span> <span class="label-free label-icons">FREE</span><span class="label-icons label-pro">PRO</span><span class="label-icons label-popular">POPULAR</span><span class="label-community label-icons">COMMUNITY CHOICE</span>```

Option doRemoveSpacesBetweenTags() is not set.

Thanks!

**Comment by voku** [comment]
Thanks for the bug report. Fixed in version 4.0.7.
