### ISSUE TITLE
Request: removeHttpPrefix to remove https (also to work with srcset attribute)

### ISSUE THREAD

**Issue by abuyoyo** [voku/HtmlMin#43]
#### What is this feature about (expected vs actual behaviour)?
1. Allow removing of `https:` as well as `http:` prefixes.
I believe this should be done by the existing function. A single function that removes both schemes is optimal IMO.

2. Also remove prefix from `srcset` attribute as well as `src` attribute.
This is technically a separate issue but it's all to do with the same hunk of code.

#### Does it take minutes, hours or days to fix?
It takes a few seconds to fix.

**Comment by voku** [comment]
1.

> "single function that removes both schemes"

But then you will have problems with links, if you're currently using "http", so all links also will use "http", please test what you are doing :)

PS: I added "doRemoveHttpsPrefixFromAttributes()"

2. ```srcset``` is also implemented for "http" and "https": https://github.com/voku/HtmlMin/commit/61ae49b5010bc46d056ae0786e338c699158b35e

--- 

changes are available in version 4.1.0

**Comment by abuyoyo** [comment]
Thank you.
I'll look into it now.

Slightly related question:
Removing the shema prefix (be it `http` or `https` ) from links is *technically* destructive to the information in `href`/`rel=external` anyway. As opposed, in a sense, to removing the schema prefix from resources used by the actual html page being processed (scripts, img tags etc.)

So perhaps an option should be made available - so as to be able to clear (either) schema from page resources without altering href/external links. Just a thought. Not relevant to my use-case. I can manage with the above change.

Also, would you consider an option similar to `removePrefix`, something like `makeRelative`. An option to minify all same-server links by making them relative, ie. those prefixed `$_SERVER['SERVER_NAME']` (and the same schema?) could be filtered to be relative. This would be considered a non-destructive minification option.

**Comment by voku** [comment]
@abuyoyo I like your idea, maybe you can create a pull request for this change?
