### ISSUE TITLE
Deprecated script MIME type not omitted on inline scripts

### ISSUE THREAD

**Issue by abuyoyo** [voku/HtmlMin#46]
Deprecated MIME type not omitted on inline scripts:
```
<script type="text/javascript">alert("Hello");</script>
```
minifies to:
```
<script type=text/javascript>alert("Hello");</script>
```

should minify to:
```
<script>alert("Hello");</script>
```

https://validator.w3.org/ flags this as 

> Warning: The `type` attribute is unnecessary for JavaScript resources.

**Comment by voku** [comment]
Thanks for the bug report and for the fix. It's fixed in version 4.3.0
