### ISSUE TITLE
HTML closing tag into script text/template (escaping slash character)

### ISSUE THREAD

**Issue by hiryu85** [voku/HtmlMin#49]
Hi voku, thanks for this library ;-).

Have a question about minify, about HTML into my `<script type="text/template">`. The output return by compressor escaping the slash of my closing tag.

```
$htmlMin = new \voku\helper\HtmlMin();
$htmlMin->doOptimizeViaHtmlDomParser(true);
return $htmlMin->minify('
     <script id="comment-loader" type="text/x-handlebars-template">
         <nocompress>
             <i class="fas fa-spinner fa-pulse"></i> Loading ... 
          </nocompress>
     </script>
 ');
```

This code return (escaping </i> with <\/i>)
```
<script id="comment-loader" type="text/x-handlebars-template">
    <i class="fas fa-spinner fa-pulse"><\/i>
     Loading ...
</script>
```

Shouldn't it return the closing tag without escaping the slash character? It is into a script[type=text/template].
And <nocompress> tag not seems work.

**Comment by voku** [comment]
Thanks for the bug report, :+1:  fixed in version 4.4.1.
