### ISSUE TITLE
Allow special HTML comments

### ISSUE THREAD

**Issue by georgringer** [voku/HtmlMin#52]
#### What is this feature about (expected vs actual behaviour)?

I have just created a small plugin https://packagist.org/packages/studiomitte/html-min which is mainly a wrapper for your package for the Open Source CMS TYPO3. 

However TYPO3 sets for uncached parts of the content some HTML comments which are later then replaced by uncached code. Because of various reasons I would like to minimize the HTML markup before this replacement which doesn't work anymore as those html comments are stripped away

#### How can I reproduce it?

It would be cool to have an option to keep comments, e.g. those starting with `<!--INT_SCRIPT`

#### Does it take minutes, hours or days to fix?

I got no clue :(

#### Any additional information?

**Comment by voku** [comment]
In version 4.4.5 you can use HtmlMin->setSpecialHtmlComments() to configure your special html comments.

⇾ https://github.com/voku/HtmlMin/commit/5efab310ee6add5a06252e6ee7b6a016405e7500#diff-468b8a043eb54ed31edbee53141c1512R1148
