### ISSUE TITLE
Problems with <wbr> tags

### ISSUE THREAD

**Issue by Fantella1978** [voku/HtmlMin#53]
#### What is this feature about (expected vs actual behaviour)?

I started using HtmlMin and a couple of days later noticed such an error. It's better to look at it by example. Trying to minimize html:

```
<blockquote class="bg-gray primary">
	<p class="text-monospace">
Malwarebytes<br>
www.malwarebytes.com<br>
User: User-\<wbr>u00d0\<wbr>u009f\<wbr>u00d0\<wbr>u009a\<wbr>User<br>
<br>
Windows (WMI): 0<br>
(end)<br>
	</p>
</blockquote>
```
As a result, we get extra tags </wbr>in the end.

`<blockquote class="bg-gray primary"><p class=text-monospace> Malwarebytes<br> www.malwarebytes.com<br> User: User-\<wbr>u00d0\<wbr>u009f\<wbr>u00d0\<wbr>u009a\<wbr>User<br> <br> Windows (WMI): 0<br> (end)<br> </wbr></wbr></wbr> </blockquote>
`

And if html has about 123 or more <wbr>, then get the result at the end of 123 or more </wbr> and then html is trimmed and lost.

#### How can I reproduce it?

As a result, I lose the end of the page, you can see here: https://sector.biz.ua/docs/tiworker_exe_bitcoin_miner_riched32_dll/tiworker_exe_bitcoin_miner_riched32_dll.phtml

#### Any additional information?

**Comment by voku** [comment]
fixed in version 4.4.4
