### ISSUE TITLE
Less-Than Sign

### ISSUE THREAD

**Issue by illuminati0n** [voku/HtmlMin#54]
#### How can I reproduce it?
I have a table with specifications.
`<table>    <tr>        <td><3</td>    </tr></table>`

And i use:
`$htmlMin->doRemoveOmmitedHtmlTags(false);
$htmlMin->minify($table);`

I want:
`<table><tr><td><3</td></tr></table>`

I got:
`<table><tr><td></td></tr></table>`

How can I save <3 in html?

**Comment by voku** [comment]
![Screenshot_20200709-165838](https://user-images.githubusercontent.com/264695/87056139-8037ff80-c205-11ea-8293-122ac0917b49.png)

https://validator.w3.org/nu/#textarea

**Comment by illuminati0n** [comment]
Ok, sorry.
Thanks.
