### ISSUE TITLE
HtmlMin cut html at the end of page

### ISSUE THREAD

**Issue by Fantella1978** [voku/HtmlMin#55]
#### What is this feature about (expected vs actual behaviour)?

HtmlMin cut html code at the end of html page

#### How can I reproduce it?

Example page without use HtmlMin:
[https://sector.biz.ua/docs/tiworker_exe_bitcoin_miner_riched32_dll/page-no-htmlmin.phtml](https://sector.biz.ua/docs/tiworker_exe_bitcoin_miner_riched32_dll/page-no-htmlmin.phtml)

Example page with HtmlMin:
[https://sector.biz.ua/docs/tiworker_exe_bitcoin_miner_riched32_dll/page-with-htmlmin.phtml](https://sector.biz.ua/docs/tiworker_exe_bitcoin_miner_riched32_dll/page-with-htmlmin.phtml)

see difference in pagesources

#### Does it take minutes, hours or days to fix?

i don't know

#### Any additional information?

**Comment by voku** [comment]
ref: https://github.com/voku/simple_html_dom/issues/50

**Comment by voku** [comment]
ref: https://github.com/voku/simple_html_dom/issues/50

**Comment by voku** [comment]
Fixed in version 4.4.6

Thanks for the bug report. :+1:

**Comment by Fantella1978** [comment]
Sorry, but not fixat yet.

**Comment by voku** [comment]
My test with invalid html passed? 🤔 Can you give me a small example of the problem, so that I can use it as test-case? Thanks.

**Comment by Fantella1978** [comment]
[view-source:https://sector.biz.ua/docs/tiworker_exe_bitcoin_miner_riched32_dll/page-no-htmlmin.phtml](page source)

**Comment by voku** [comment]
The error was that php DOMDocument tries to close the ```<wbr>``` tags with ```</wbr>``` ... so now we will re-write the self-closing tags to e.g. ```<wbr/>```.

Please try version 4.4.7

**Comment by Fantella1978** [comment]
Tested the version 4.4.7

HtmlMin dont't cut html code :) It's good!  BUT,  in minified html disappeared tags:   `<head>, </head>, </body>, </html>`. It's no good!

**Comment by voku** [comment]
:+1:  

The problem was that DOMDocument from php cannot handle the input if there are content before the doctype, so we now remove it and it's working as expected. Fixed in version 4.4.8.

**Comment by Fantella1978** [comment]
Tested version 4.4.8.

Disappeared tags: </head>, </body>, </html>. Validator as a result of verification does not find errors.

**Comment by voku** [comment]
HtmlMin will remove not needed end-tags: https://html.spec.whatwg.org/multipage/syntax.html#syntax-tag-omission

**Comment by Fantella1978** [comment]
Well, then we close the issue.
